### PR TITLE
Fix recipe to include click-help-colors

### PR DESCRIPTION
**Pull request by rbellamy**
Before fix, with fresh conda environment:

```python
% molecule --version
Traceback (most recent call last):
  File "/home/rbellamy/Development/Terradatum/ansible-role-edb/conda-env/bin/molecule", line 6, in <module>
    from molecule.__main__ import main
  File "/home/rbellamy/Development/Terradatum/ansible-role-edb/conda-env/lib/python3.8/site-packages/molecule/__main__.py", line 22, in <module>
    from molecule.shell import main
  File "/home/rbellamy/Development/Terradatum/ansible-role-edb/conda-env/lib/python3.8/site-packages/molecule/shell.py", line 31, in <module>
    from molecule import command
  File "/home/rbellamy/Development/Terradatum/ansible-role-edb/conda-env/lib/python3.8/site-packages/molecule/command/__init__.py", line 27, in <module>
    from molecule.command import base  # noqa
  File "/home/rbellamy/Development/Terradatum/ansible-role-edb/conda-env/lib/python3.8/site-packages/molecule/command/base.py", line 35, in <module>
    from click_help_colors import HelpColorsCommand, HelpColorsGroup
ModuleNotFoundError: No module named 'click_help_colors'
zsh: exit 1     molecule --version
```

After install `click-help-colors-0.8`, `molecule` works.

@conda-forge-admin, please rerender

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bgruening** [comment]
@rbellamy can you add `molecule --version` as test?

**Comment by rbellamy** [comment]
```console
% molecule --version
molecule 3.0.4
   ansible==2.9.7 python==3.8
```

**Comment by rbellamy** [comment]
Or maybe I'm missing what you're really asking for @bgruening - were you asking for an example run after the installation of `click-helper-colors` or something else? This is my first time working with a feedstock repo, and am not finding tests in this repo?

**Comment by bgruening** [comment]
You can add something like:

```
test:
   imports:
     - molecule
  commands:
    - molecule --version
```

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
